services:
  - type: web
    name: birlikte-web
    runtime: static
    buildCommand: npm ci && npm run build:web
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
